# Generated by Django 3.0.6 on 2020-06-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querymodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
    ]
