# Generated by Django 3.0.6 on 2020-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymodels', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
