# Generated by Django 3.0.5 on 2020-05-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_msg', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=300)),
                ('objet', models.CharField(max_length=300)),
                ('date_courrier', models.DateField()),
                ('date_reception', models.DateField()),
                ('type_message', models.CharField(max_length=100)),
                ('usager_insert', models.CharField(max_length=100, null=True)),
                ('date_insert', models.DateTimeField()),
                ('usager_update', models.CharField(max_length=100, null=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_srv', models.CharField(max_length=100)),
                ('nom_service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crimputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_imput', models.DateField()),
                ('date_lmt_trmt', models.DateField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('statut_msg', models.CharField(max_length=15)),
                ('usager_insert', models.CharField(max_length=100, null=True)),
                ('date_insert', models.DateTimeField()),
                ('usager_update', models.CharField(max_length=100, null=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('crmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcour.Crmessage')),
                ('crservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcour.Crservice')),
            ],
        ),
    ]
