# Generated by Django 3.0.6 on 2020-06-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0003_auto_20200603_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='clbaseviews.Subject'),
        ),
    ]
