# Generated by Django 3.0.6 on 2020-06-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0004_auto_20200603_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
