# Generated by Django 3.0.6 on 2020-06-05 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0006_company_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='social_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
