# Generated by Django 3.0.6 on 2020-06-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0007_person_social_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
