# Generated by Django 3.0.6 on 2020-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0008_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('social_code', models.CharField(max_length=5)),
            ],
        ),
    ]
