# Generated by Django 3.0.6 on 2020-06-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0011_auto_20200615_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
