# Generated by Django 3.0.6 on 2020-06-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0013_reponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='reponse',
            old_name='content',
            new_name='contenu',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='title',
        ),
    ]
