# Generated by Django 3.0.6 on 2020-11-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0014_auto_20200617_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='slug', editable=False, unique=True),
        ),
    ]
