# Generated by Django 3.0.6 on 2020-11-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clbaseviews', '0016_auto_20201121_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
