# Generated by Django 3.0.5 on 2020-05-31 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('matiere', models.CharField(max_length=200)),
                ('classroom', models.CharField(choices=[('', 'Serie...'), ('TSE', 'TSE (Terminale Sciences Exactes)'), ('TLL', 'TLL (Terminale Lettres et Litteratures)'), ('TSS', 'TSS (Terminale Sciences Sociales)'), ('TSECO', 'TSECO (Terminale Sciences Economiques)'), ('TSEXP', 'TSEXP (Terminale Sciences Expérimentales)')], max_length=100)),
                ('coefficient', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='')),
                ('page_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image_file', models.ImageField(upload_to='')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='subjects.Subject')),
            ],
        ),
    ]
