# Generated by Django 3.0.5 on 2020-06-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200601_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('year', 'matiere', 'classroom')},
        ),
    ]
